### PR TITLE
Basic refactoring and cleanup

### PR DESCRIPTION
**Pull request by romainrichard**
As promised on Reddit :slightly_smiling_face: 

- Replaced tabs with 4 spaces
- Replaced a, b, c, ... variables with the sounds variable
- Factorized the handling of key presses

There's still a lot to do to clean up the code, this should be easier now with this refactoring, plus I think you should go through that exercise yourself as it'll help you write better code in the future.
You should run tools like [flake8](https://pypi.org/project/flake8/) and [pylint](https://pypi.org/project/pylint/), they'll tell you what you need to change.

### CODE REVIEW

**Review by jsoncz — CHANGES_REQUESTED** [review]
Hey! I really appreciate your efforts, you've pointed me in the right direction. Unfortunately there is a slight change in behaviour which is not good, when pressing multiple buttons the sound kind of glitches and continues to play the whole audio sample [because all sounds are stored as sound.play() or sound.stop()] - but in the original version when each a, b, c represents it's own variable each sound can be controlled individually. I hope that makes sense!

**Comment by romainrichard** [comment]
Woops! I'm not sure I'm getting it though. Could you provide step by step instructions on how to reproduce that issue?

**Comment by jsoncz** [comment]
Yep, basically Numpadz should be really button smashing friendly. When you hit a key, it should only play for as long as that key is held down (not play the whole sample) but when you hit a few keys at once, the first keys you have pressed continue to play the sample completely even if you have released your finger from that key. That is because of the variable assignment to the files. If you test the original code and bash a lot of keys repeatedly you will hear the difference I hope :).

I'm still really happy you helped to refactor the code, however the functionality has to sound like the original code. I know my code is really messy and amatuer, but it works. I'm about to commit some new changes...quite a lot, and I'm sure you will be horrified with the code :D but if you are up for the challenge or want to add some new feature, please go ahead - I'm happy to try and co operate!

**Comment by romainrichard** [comment]
The code should be working now. I'm closing this PR because it won't be easy to merge in. I'd suggest you try to replicate the changes I've suggested in that PR (I can explain why I did those in more details if you have questions).

**Comment by jsoncz** [comment]
Thanks a lot! I will try my best.

**Review by jsoncz — COMMENTED** [review]
Thanks Rich, I've implemented your refactoring into my newer version! have a look :)

**Comment by romainrichard** [comment]
Looks great!

Here's what I think you should focus on next:
1. Factorization: find duplicated lines and see if you could simplify your code.
For example:
```
                try:
                    selectedGifPack += 1
                    gp = gifpacks[selectedGifPack]
                    print(gp)
                except (IndexError):
                    selectedGifPack = 0
                    gp = gifpacks[selectedGifPack]
                    print(gp)
```
could be simplified to:
```
                try:
                    selectedGifPack += 1
                    gp = gifpacks[selectedGifPack]
                except (IndexError):
                    selectedGifPack = 0
                    gp = gifpacks[selectedGifPack]
                print(gp)
```

2. It's good practice, when writing a `try..except`, to only have lines that could cause the exception(s) you're trying to catch in the `try` statement.
For example:
```
                try:
                    selectedGifPack += 1
                    gp = gifpacks[selectedGifPack]
                except (IndexError):
                    selectedGifPack = 0
                    gp = gifpacks[selectedGifPack]
                print(gp)
```
could be simplified to:
```
                selectedGifPack += 1
                try:
                    gp = gifpacks[selectedGifPack]
                except (IndexError):
                    selectedGifPack = 0
                    gp = gifpacks[selectedGifPack]
                print(gp)
```

3. Run [flake8](https://pypi.org/project/flake8/) and [pylint](https://pypi.org/project/pylint/)

4. Create functions: one example is how many times the code to create the `sounds` variable is duplicated. Would be nice to have a function that you could pass the selected pack to as argument and it would return the list of corresponding sounds.
Ideally, as much of your code as possible should be in functions. I'd suggest looking at http://thepythonguru.com/what-is-if-__name__-__main__/ or https://stackoverflow.com/questions/419163/what-does-if-name-main-do for ideas on why and how you would do that.

5. Always specify the exceptions you're catching
For example:
```
try:
    packs = []
    packs = [line.rstrip('\n') for line in open('wav/packlist.txt')]
    print ("NUMPADZ - Cycle through Packs with + / -")
    print (packs)

except:
    print ("could not open packlist, check you run from the current dir")
```
should be:
```
try:
    packs = []
    packs = [line.rstrip('\n') for line in open('wav/packlist.txt')]
    print ("NUMPADZ - Cycle through Packs with + / -")
    print (packs)

except IOError:
    print ("could not open packlist, check you run from the current dir")
```

6. Exit if something is wrong
For example:
```
try:
    packs = []
    packs = [line.rstrip('\n') for line in open('wav/packlist.txt')]
    print ("NUMPADZ - Cycle through Packs with + / -")
    print (packs)

except IOError:
    print ("could not open packlist, check you run from the current dir")
```
could be (just as an example, probably won't look like that after refactoring):
```
try:
    packs = []
    packs = [line.rstrip('\n') for line in open('wav/packlist.txt')]
    print ("NUMPADZ - Cycle through Packs with + / -")
    print (packs)

except IOError:
    print ("could not open packlist, check you run from the current dir")
    sys.exit()
```

If you're unsure about some of your changes, I can definitely help review them if instead of pushing to `master` you created a PR for it so don't hesitate to add me as a reviewer if you want me to.

**Comment by jsoncz** [comment]
Hi Rich, thanks again for your great input! I've had a lot of fun with this, seriously. I'm going to consider what you've said and make some updates. 

It's great to have your feedback! This is one of my first projects and it's awesome to learn more with a reviewer :)

**Comment by jsoncz** [comment]
Rich, I have tried to do as you advised as much as I could so far. As for functions, the reason I'm not using many functions is because I don't yet understand async. Previously I tried to add a function to create a visualisation based on the wav file - but it would interfere with the audio playing... I'm researching it now, any recommendations for calling a function without interferring with the keydown sound play statement?

Because the keydown function is kind of a loop that is counting every tick that the key is held, functions that start during that process kind of screw it up.

**Comment by romainrichard** [comment]
You don't need to know about async to write functions. Maybe you were trying to do something too complicated.
I'd start with something simple. For example, look how many times you wrote the following:
```
SOUNDS = [pygame.mixer.Sound("wav/{}/{:04}.wav".format(P, i))
          for i in range(1, 10)]
```
Wouldn't it be nice if you didn't have to remember that whole construction phase every time?
Well, you could create a function that does it for you:
```
def get_sounds(pack):
    return [pygame.mixer.Sound("wav/{}/{:04}.wav".format(pack, i))
            for i in range(1, 10)]
```
And now all the lines where you were redefining sounds, you should be able to do:
```
SOUNDS = get_sounds(P)
```
Then go from there and see what else you could improve.

**Comment by jsoncz** [comment]
Great, I understand. I've created get_sounds and get_gifs function as you suggested :).
I'd really like to have some kind of graphic movement while the sound is playing, and I've got close to this effect, but there's always something not right! That's why I was thinking about async functions, but I probably have mis-understood it. Anyway, thanks again for your help!

**Comment by jsoncz** [comment]
I've added numpadz_VISUALISER.py to the project, just so you can see what I was trying to achieve, however It is broken and really badly coded, I was just trying to hack it together.

**Pull request closed without merging**
